import type { TerminDriver } from "@/components/admin/AdminTerminDriversTable";

// Placeholder data — will be replaced with a real Supabase query filtered
// by the termin id. Respects the rule that a missing form always implies
// payment status "čaka" (a driver can't have paid or been sent a payment
// before they've even filled out the registration form). Shared between the
// termin detail page and the driver edit page so both seed the same
// localStorage-backed list (see admin-drivers-store.ts) regardless of which
// page is opened first.
export const PLACEHOLDER_DRIVERS: TerminDriver[] = [
  {
    id: "1",
    driverName: "Janez Novak",
    email: "janez.novak@example.com",
    phone: "+386 41 123 456",
    registrationDate: "20.04.2026",
    dateOfBirth: "12.03.1988",
    birthPlace: "Kranj",
    birthCountry: "Slovenija",
    citizenship: "Slovensko",
    emso: "1203988500123",
    address: "Cesta na Brdo 12, 4000 Kranj",
    categoryC: true,
    formStatus: "izpolnjen",
    paymentStatus: "poravnano",
    payer: "sam",
    paymentMethod: "Nakazilo",
    paymentAmount: "50 EUR",
    paymentReference: "TC-284",
  },
  {
    id: "2",
    driverName: "Ana Kovač",
    email: "ana.kovac@example.com",
    phone: "+386 31 987 654",
    registrationDate: "18.04.2026",
    dateOfBirth: "24.07.1991",
    birthPlace: "Ljubljana",
    birthCountry: "Slovenija",
    citizenship: "Slovensko",
    emso: "2407991505234",
    address: "Dunajska cesta 45, 1000 Ljubljana",
    categoryD: true,
    formStatus: "izpolnjen",
    paymentStatus: "poslano",
    payer: "Kobal d.o.o.",
    paymentMethod: "Nakazilo (podjetje)",
    paymentAmount: "50 EUR",
    paymentReference: "TC-285",
  },
  {
    id: "3",
    driverName: "Marko Zupan",
    email: "marko.zupan@example.com",
    phone: "+386 40 555 111",
    registrationDate: "22.05.2026",
    formStatus: "manjka",
    paymentStatus: "caka",
    payer: "sam",
  },
  {
    id: "4",
    driverName: "Petra Horvat",
    email: "petra.horvat@example.com",
    phone: "+386 51 333 111",
    registrationDate: "03.03.2026",
    dateOfBirth: "05.11.1985",
    categoryC: true,
    formStatus: "izpolnjen",
    paymentStatus: "poravnano",
    payer: "Arriva",
  },
  {
    id: "5",
    driverName: "Luka Bregar",
    email: "luka.bregar@example.com",
    phone: "+386 41 777 888",
    registrationDate: "10.05.2026",
    dateOfBirth: "18.09.1993",
    categoryD: true,
    formStatus: "izpolnjen",
    paymentStatus: "caka",
    payer: "sam",
  },
  {
    id: "6",
    driverName: "Nina Potočnik",
    email: "nina.potocnik@example.com",
    phone: "+386 40 555 222",
    registrationDate: "28.05.2026",
    formStatus: "manjka",
    paymentStatus: "caka",
    payer: "sam",
  },
  {
    id: "7",
    driverName: "Rok Kranjc",
    email: "rok.kranjc@example.com",
    phone: "+386 41 456 789",
    registrationDate: "15.02.2026",
    dateOfBirth: "30.01.1990",
    categoryC: true,
    categoryD: true,
    formStatus: "izpolnjen",
    paymentStatus: "poslano",
    payer: "Jurenič Transport",
  },
  {
    id: "8",
    driverName: "Maja Vidmar",
    email: "maja.vidmar@example.com",
    phone: "+386 51 222 333",
    registrationDate: "05.06.2026",
    dateOfBirth: "09.06.1987",
    categoryD: true,
    formStatus: "izpolnjen",
    paymentStatus: "poravnano",
    payer: "sam",
  },
];
