import countriesEn from "./countries-en.json";
import countriesSr from "./countries-sr.json";

// Slovenian country names for the obrazec's country dropdowns. The first
// 10 are the most common countries of origin for professional C/D drivers
// working in Slovenia (Balkan/Eastern European labor migration into the
// transport sector) — a reasoned estimate, not official statistics, listed
// first so the majority of users don't have to scroll. The rest follow
// alphabetically (A–Z).
const COMMON_COUNTRIES_SL = [
  "Slovenija",
  "Bosna in Hercegovina",
  "Srbija",
  "Hrvaška",
  "Severna Makedonija",
  "Kosovo",
  "Črna gora",
  "Ukrajina",
  "Albanija",
  "Bolgarija",
];

const OTHER_COUNTRIES_SL = [
  "Andora",
  "Angola",
  "Argentina",
  "Armenija",
  "Avstralija",
  "Avstrija",
  "Azerbajdžan",
  "Bahami",
  "Bahrajn",
  "Bangladeš",
  "Belgija",
  "Belize",
  "Belorusija",
  "Benin",
  "Bocvana",
  "Bolivija",
  "Brazilija",
  "Brunej",
  "Burkina Faso",
  "Burundi",
  "Butan",
  "Ciper",
  "Čad",
  "Češka",
  "Čile",
  "Danska",
  "Dominikanska republika",
  "Džibuti",
  "Egipt",
  "Ekvador",
  "Ekvatorialna Gvineja",
  "Eritreja",
  "Estonija",
  "Esvatini",
  "Etiopija",
  "Fidži",
  "Filipini",
  "Finska",
  "Francija",
  "Gabon",
  "Gambija",
  "Gana",
  "Grčija",
  "Gruzija",
  "Gvajana",
  "Gvatemala",
  "Gvineja",
  "Gvineja Bissau",
  "Haiti",
  "Honduras",
  "Indija",
  "Indonezija",
  "Irak",
  "Iran",
  "Irska",
  "Islandija",
  "Italija",
  "Izrael",
  "Jamajka",
  "Japonska",
  "Jemen",
  "Jordanija",
  "Južna Afrika",
  "Južna Koreja",
  "Južni Sudan",
  "Kambodža",
  "Kamerun",
  "Kanada",
  "Katar",
  "Kazahstan",
  "Kenija",
  "Kirgizistan",
  "Kiribati",
  "Kitajska",
  "Kolumbija",
  "Kongo",
  "Kostarika",
  "Kuba",
  "Kuvajt",
  "Laos",
  "Lesoto",
  "Letonija",
  "Libanon",
  "Liberija",
  "Libija",
  "Lihtenštajn",
  "Litva",
  "Luksemburg",
  "Madagaskar",
  "Madžarska",
  "Malavi",
  "Maldivi",
  "Malezija",
  "Mali",
  "Malta",
  "Maroko",
  "Mavretanija",
  "Mavricij",
  "Mehika",
  "Mikronezija",
  "Moldavija",
  "Monako",
  "Mongolija",
  "Mozambik",
  "Mjanmar",
  "Namibija",
  "Nauru",
  "Nemčija",
  "Nepal",
  "Niger",
  "Nigerija",
  "Nikaragva",
  "Nizozemska",
  "Norveška",
  "Nova Zelandija",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua Nova Gvineja",
  "Paragvaj",
  "Peru",
  "Poljska",
  "Portugalska",
  "Romunija",
  "Rusija",
  "Ruanda",
  "Salomonovi otoki",
  "Salvador",
  "Samoa",
  "San Marino",
  "Saudova Arabija",
  "Sejšeli",
  "Senegal",
  "Sierra Leone",
  "Singapur",
  "Sirija",
  "Slovaška",
  "Somalija",
  "Srednjeafriška republika",
  "Sudan",
  "Surinam",
  "Španija",
  "Šrilanka",
  "Švedska",
  "Švica",
  "Tadžikistan",
  "Tajska",
  "Tajvan",
  "Tanzanija",
  "Togo",
  "Tonga",
  "Trinidad in Tobago",
  "Tunizija",
  "Turčija",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Urugvaj",
  "Uzbekistan",
  "Vanuatu",
  "Vatikan",
  "Velika Britanija",
  "Venezuela",
  "Vietnam",
  "Vzhodni Timor",
  "Zambija",
  "Združeni arabski emirati",
  "Združene države Amerike",
  "Zelenortski otoki",
  "Zimbabve",
].sort((a, b) => a.localeCompare(b, "sl"));

// Same country list translated for each site locale — index-aligned with
// the Slovenian arrays above (see countries-en.json / countries-sr.json).
const COUNTRIES_BY_LOCALE: Record<string, string[]> = {
  sl: [...COMMON_COUNTRIES_SL, ...OTHER_COUNTRIES_SL],
  en: [...countriesEn.common, ...countriesEn.other],
  sr: [...countriesSr.common, ...countriesSr.other],
};

export function getCountries(locale: string): string[] {
  return COUNTRIES_BY_LOCALE[locale] ?? COUNTRIES_BY_LOCALE.sl;
}
